### ISSUE TITLE
Use concentric circles to account for intersection specificity

### ISSUE THREAD

**Issue by emilyfuhrman** [emilyfuhrman/F2015020#9]

**Comment by emilyfuhrman** [comment]
I'm thinking this could mean removing the outermost circle, sizing the central solid one based on the number of certain intersections, and sizing the circle surrounding the central one based on the _sum_ of certain and uncertain intersections.

**Comment by buck-work** [comment]
Yes, I had been thinking the same thing (haven't figured out how to code it yet, but that's what I was looking into). Will follow through on this.

**Comment by buck-work** [comment]
my pull request should take care of this issue on a technical level. maybe the styling needs to be adjusted so that it's more visible? let me know if you want me to address that, or if you want to. I'm happy to play around with it, though not so experienced with choosing pleasing styles.
-b

**Comment by emilyfuhrman** [comment]
Thanks! Sorry it took me so long to get to this -- everything looks good on my end. Nice work. We can discuss a bit more at today's meeting.
